# Location of top-level MicroPython directory
MPY_DIR = ../../../../

# Name of module
MOD = picante

# Source files (.c or .py)
SRC = picante_c.c cmdQueue.c font.c graphics.c audio.c picante.py

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = armv6m


# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk


